ndk-version: r28c
          link-to-sdk: true

      - name: Grant Execute Permission to gradlew
        run: chmod +x ./gradlew

      - name: Inject API Keys
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        run: echo "curseforge.api_key=${CF_API_KEY}" >> local.properties

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: LeviLauncher-Modded-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Release APK to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
